services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Passionweb\AiSeoHelper\:
    resource: '../Classes/*'

  Passionweb\AiSeoHelper\Controller\Ajax\AiController:
    public: true

  Passionweb\AiSeoHelper\Service\ContentService:
    public: true
